### PR TITLE
Allow matching for the discovery based upon manufacturerData uuid

### PR DESCRIPTION
**Pull request by reconbot**

### CODE REVIEW

**Comment by sandeepmistry** [comment]
This change was needed because @reconbot renamed his drone to "AttackWizard" via the Parrot mobile app.

**Comment by rwaldron** [comment]
I would love to know more about the relevance of the color :D

**Comment by sandeepmistry** [comment]
Doesn't look like the manufacturer data has anything to do with color, the white model advertises the same ```4300cf1900090100```.

**Comment by voodootikigod** [comment]
LocalName normally has indication of color. 

Has this been tested with OOTB drones?

**Pull request merged**
